### ISSUE TITLE
csv source

### ISSUE THREAD

**Issue by baborok** [roflame/Xfmr-Fault-Type-Prediction#2]
Hello! Can you help please ? Нou have a following line in code
ratios = pd.read_csv('')
classes = pd.read_csv('')
test = pd.read_csv('')
test_classes = pd.read_csv('')
What csv does it refer to ?
data = pd.read_csv('')
this also

**Comment by rohanraghuraman** [comment]
These are the datasets I used to train the model on. As I explained in my README, I have provided the format of the datasets but cannot provide the actual data as that is proprietary.
